import test from 'node:test';import assert from 'node:assert/strict';
import {R,REF,HEAD} from './helpers.mjs';
test('valid repository and case-insensitive cache key',()=>assert.equal(R.key({owner:'Octo',repo:'Demo'}),'octo/demo'));
for(const input of ['https://evil.example/octo/demo','https://github.com/settings/tokens','https://github.com/notifications','https://user:pass@github.com/octo/demo','https://github.com/orgs/octo','https://github.com/octo/%2Fsecret'])test(`reject non-repository URL: ${input}`,()=>assert.equal(R.parseRepo(input),null));
test('repository subpages remain associated with their repository',()=>assert.deepEqual(R.parseRepo('https://github.com/octo/demo/tree/feature/a'),REF));
for(const path of ['../secrets','src/../a','/src','a//b','a%2fb','a\\b','a?ref=x','a#x','a/b/c/d/e/f'])test(`reject unsafe directory: ${path}`,()=>assert.throws(()=>R.path(path),e=>e.code==='INVALID_INPUT'));
test('unicode directory and spaces are valid',()=>assert.equal(R.path('examples/한국어 demo'),'examples/한국어 demo'));
test('evidence uses a pinned SHA and escaped filename',()=>assert.equal(R.fileUrl(REF,HEAD,'demo a/x#y.txt',7),`https://github.com/octo/demo/blob/${HEAD}/demo%20a/x%23y.txt#L7`));
test('redaction removes token-like strings and password values',()=>{const s=R.clean('TOKEN=github_pat_abcdefghijklmnopqrstuvwxyz password=hunter123');assert(!s.includes('abcdefghijklmnopqrstuvwxyz'));assert(!s.includes('hunter123'));});
test('display text neutralizes bidi control characters',()=>assert.equal(R.clean('a\u202eb'),'a\uFFFDb'));
test('environment secret files are not allowlisted',()=>{for(const n of ['.env','.env.local','.npmrc','id_rsa','secrets.json'])assert(!R.sourceNames.includes(n));});
test('language and error dictionaries have matching keys',()=>{assert.deepEqual(Object.keys(R.strings.en).sort(),Object.keys(R.strings.ko).sort());assert.deepEqual(Object.keys(R.strings.en.errors).sort(),Object.keys(R.strings.ko.errors).sort());});
const sender={id:'test',url:'https://github.com/octo/demo',tab:{id:1},frameId:0};
test('content messages can request their own analysis',()=>assert.equal(R.authorize({namespace:'RepoRun',type:'ANALYZE',ref:REF},sender,'test'),false));
for(const type of ['TOKEN','OPTIONS','DIAGNOSTICS','CLEAR'])test(`content cannot call privileged ${type}`,()=>assert.throws(()=>R.authorize({namespace:'RepoRun',type,ref:REF},sender,'test')));
test('content cannot analyze a different repository',()=>assert.throws(()=>R.authorize({namespace:'RepoRun',type:'ANALYZE',ref:{owner:'other',repo:'private'}},sender,'test')));
test('messages from nested frames are denied',()=>assert.throws(()=>R.authorize({namespace:'RepoRun',type:'ANALYZE',ref:REF},{...sender,frameId:2},'test')));
test('foreign extension ID is denied',()=>assert.throws(()=>R.authorize({namespace:'RepoRun',type:'BOOT'}, {id:'evil',url:'chrome-extension://test/options.html'},'test')));
test('trusted extension page can manage a token',()=>assert.equal(R.authorize({namespace:'RepoRun',type:'TOKEN'}, {id:'test',url:'chrome-extension://test/options.html'},'test'),true));
