"""Real Chromium DOM/responsive QA with the shipped placement logic.
GitHub layout variants, Chrome APIs and analysis responses are controlled fixtures.
"""
from pathlib import Path
import os, shutil, json
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]
ns={'__file__':str(ROOT/'tests/browser_qa.py')}
exec((ROOT/'tests/browser_qa.py').read_text().split('with sync_playwright() as p:')[0],ns)
checks=[]
def check(name,ok):
    checks.append({'name':name,'pass':bool(ok)})
    if not ok: raise AssertionError(name)
def mode(page,value):
    page.wait_for_selector(f'#reporun-button-host[data-placement="{value}"]',state='attached',timeout=6000)
    page.wait_for_timeout(180)
def shot(page,name): page.screenshot(path=str(ROOT/'docs/screenshots'/name))
with sync_playwright() as p:
    browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH') or shutil.which('chromium'),headless=True,args=['--no-sandbox'])
    context,page=ns['setup'](browser,width=1440,height=950)
    mode(page,'sidebar')
    before=page.locator('.pagehead-actions').inner_html()
    check('launcher is inside About, not Releases',page.locator('[data-fixture-about-row] #reporun-button-host').count()==1)
    check('no RepoRun launcher in repository header',page.locator('#repository-container-header #reporun-button-host').count()==0)
    check('one launcher total',page.locator('#reporun-button-host').count()==1)
    check('sidebar button has readable text',page.get_by_role('button',name='Run setup',exact=True).is_visible())
    check('sidebar has brief setup hint',page.get_by_text('Requirements before cloning',exact=True).is_visible())
    check('sidebar is not a floating panel',page.locator('#reporun-button-host').evaluate('(x)=>getComputedStyle(x).position')!='fixed')
    check('new blue SVG decoded',page.locator('#reporun-button-host img').evaluate('(x)=>x.complete&&x.naturalWidth===128'))
    check('passive launch placement makes zero API calls',page.evaluate('rrQA.calls.length')==0)
    shot(page,'09-sidebar-en-light.png')
    page.emulate_media(color_scheme='dark')
    page.evaluate('RepoRun.rpc({type:"LANGUAGE",ref:{owner:"octo",repo:"demo"},language:"ko"})')
    page.get_by_role('button',name='실행 조건',exact=True).wait_for()
    shot(page,'10-sidebar-ko-dark.png')
    check('other Repo tools and Star are unchanged',page.locator('.pagehead-actions').inner_html()==before)
    page.evaluate('window.savedLauncher=document.getElementById("reporun-button-host"); window.savedSidebar=document.querySelector(".Layout-sidebar").outerHTML')
    page.get_by_role('button',name='실행 조건',exact=True).focus()
    page.set_viewport_size({'width':430,'height':900}); mode(page,'floating')
    box=page.get_by_role('button',name='실행 조건',exact=True).bounding_box()
    check('fallback is precisely 44x44 CSS pixels',box['width']==44 and box['height']==44)
    check('fallback stays inside right/bottom safe edge',abs(box['x']+box['width']-414)<=1 and abs(box['y']+box['height']-884)<=1)
    check('fallback icon only, label hidden visually',not page.locator('.rr-launcher-copy').is_visible())
    check('fallback retains Korean accessible name',page.get_by_role('button',name='실행 조건',exact=True).count()==1)
    check('fallback relocation reuses same host and listener',page.evaluate('window.savedLauncher===document.getElementById("reporun-button-host")'))
    check('focus preserved after responsive relocation',page.evaluate('document.activeElement===savedLauncher&&savedLauncher.shadowRoot.activeElement.tagName==="BUTTON"'))
    check('tooltip available by keyboard focus',page.locator('#reporun-button-host button').evaluate('(x)=>getComputedStyle(x,"::after").content').find('RepoRun')>=0)
    page.locator('#reporun-button-host button').evaluate('(x)=>x.blur()');page.mouse.move(0,0)
    shot(page,'11-floating-ko-dark.png')
    page.get_by_role('button',name='실행 조건',exact=True).click();page.locator('.rr-facts').wait_for()
    check('fallback opens exactly one analysis panel',page.locator('#reporun-panel-host').count()==1)
    check('fallback hidden while modal is open',not page.locator('#reporun-button-host').is_visible())
    page.keyboard.press('Escape')
    check('fallback restored after modal close',page.get_by_role('button',name='실행 조건',exact=True).is_visible())
    check('focus restored after closing fallback-opened modal',page.evaluate('savedLauncher.shadowRoot.activeElement?.tagName')=='BUTTON')
    page.set_viewport_size({'width':1440,'height':950});mode(page,'sidebar')
    check('sidebar recovers after desktop resize',page.locator('[data-fixture-about-row] #reporun-button-host').count()==1)
    # Hidden or removed About sidebars must not strand the control.
    page.evaluate('document.querySelector(".Layout-sidebar").hidden=true');mode(page,'floating')
    check('hidden sidebar falls back',page.locator('body > #reporun-button-host').count()==1)
    page.evaluate('document.querySelector(".Layout-sidebar").hidden=false');mode(page,'sidebar')
    page.evaluate('document.querySelector(".Layout-sidebar").style.visibility="hidden"');mode(page,'floating')
    check('visibility hidden sidebar falls back',page.locator('#reporun-button-host').is_visible())
    page.evaluate('document.querySelector(".Layout-sidebar").style.visibility="visible"');mode(page,'sidebar')
    page.evaluate('document.querySelector(".Layout").style.display="block"');mode(page,'floating')
    check('stacked About does not receive desktop sidebar button',page.locator('body > #reporun-button-host').count()==1)
    page.evaluate('document.querySelector(".Layout").style.display="grid"');mode(page,'sidebar')
    page.evaluate('document.querySelector(".Layout-sidebar").remove()');mode(page,'floating')
    check('deleted sidebar recovers with existing host',page.evaluate('savedLauncher===document.getElementById("reporun-button-host")'))
    shot(page,'12-floating-desktop-dark.png')
    page.evaluate('document.querySelector(".Layout").insertAdjacentHTML("beforeend",savedSidebar)');mode(page,'sidebar')
    check('late loaded About automatically gains the launcher',page.locator('[data-fixture-about-row] #reporun-button-host').count()==1)
    # A cached HTML sidebar copy contains an old host. Our controller must leave
    # only the one live instance (stale host is removed by sync).
    check('no duplicated launcher after sidebar replacement',page.locator('#reporun-button-host').count()==1)
    page.evaluate('document.getElementById("reporun-button-host").remove()');mode(page,'sidebar')
    check('GitHub removing the injected node is repaired',page.evaluate('savedLauncher===document.getElementById("reporun-button-host")'))
    count=page.evaluate('rrQA.calls.length')
    page.evaluate('for(let i=0;i<40;i++){window.dispatchEvent(new Event("turbo:load"));window.dispatchEvent(new Event("resize"));}')
    page.wait_for_timeout(800)
    check('event bursts do not duplicate launcher',page.locator('#reporun-button-host').count()==1)
    check('event bursts do not trigger API scans',page.evaluate('rrQA.calls.length')==count)
    check('header remains unchanged after every relocation',page.locator('.pagehead-actions').inner_html()==before)
    # Non-BorderGrid variants and explicit About markers.
    page.evaluate('document.querySelector(".Layout-sidebar").innerHTML="<section><h2>소개</h2><p>실행 환경 안내</p></section><section><h2>Releases</h2></section>"');mode(page,'sidebar')
    check('Korean About + section markup supported',page.locator('.Layout-sidebar > section:first-child #reporun-button-host').count()==1)
    page.evaluate('document.querySelector(".Layout-sidebar").innerHTML="<div data-testid=about-section><p>Repository information</p></div>"');mode(page,'sidebar')
    check('explicit About test marker supported without English heading',page.locator('[data-testid="about-section"] #reporun-button-host').count()==1)
    page.evaluate('document.querySelector(".Layout-sidebar").innerHTML="<section><h2>Languages</h2></section>"');mode(page,'floating')
    check('unrelated sidebar section is not mistaken for About',page.locator('body > #reporun-button-host').count()==1)
    page.evaluate('document.querySelector(".Layout-sidebar").innerHTML="<div><h2>About</h2><p>Project</p><h2>Releases</h2></div>"');mode(page,'floating')
    check('ambiguous About wrapper uses fallback rather than appending below Releases',page.locator('body > #reporun-button-host').count()==1)
    # Navigation must remove both modal and launcher outside repositories.
    page.evaluate('rrQA.virtualURL="https://github.com/settings/tokens";window.dispatchEvent(new Event("popstate"));')
    page.wait_for_selector('#reporun-button-host',state='detached')
    check('non-repository navigation removes fallback',page.locator('#reporun-button-host').count()==0)
    page.evaluate('rrQA.virtualURL="https://github.com/octo/demo";window.dispatchEvent(new Event("popstate"));');mode(page,'floating')
    check('return to repository restores a single launcher',page.locator('#reporun-button-host').count()==1)
    page.evaluate('rrQA.virtualURL="https://github.com/octo/next";document.querySelector("meta[name=repository_nwo]").content="octo/next";window.dispatchEvent(new Event("soft-nav:end"));')
    page.wait_for_timeout(400)
    check('SPA repository change does not strand duplicates',page.locator('#reporun-button-host').count()==1)
    check('SPA repository change does not auto-analyze',page.evaluate('rrQA.calls.length')==count)
    context.close()
    check('no uncaught JavaScript errors',not ns['errors'])
    (ROOT/'qa-results/placement.json').write_text(json.dumps({'browser':browser.version,'checks':checks,'errors':ns['errors'],'scope':'Real Chromium layout/DOM with simulated GitHub/Chrome APIs. Not installed Chrome/GitHub certification.'},ensure_ascii=False,indent=2))
    browser.close()
print(f'Placement checks: {len(checks)} passed')
