import test from 'node:test';import assert from 'node:assert/strict';import {R,REF,HEAD,TREE,store,fixture,fakeApi} from './helpers.mjs';
async function setup(files,extra=[]){const s=store(),f=fixture(files,extra),api=fakeApi(f);await s.store.ready;return {...s,f,api,service:new R.Service(s.store,api)};}
test('one scan resolves a fixed commit and only named setup files',async()=>{const x=await setup({'package.json':'{"scripts":{"dev":"vite"}}','README.md':'# Hello','.env':'PASSWORD=secret','source.js':'evil()','index.html':'<p>x</p>','pnpm-lock.yaml':'lock'});const r=await x.service.analyze(REF);assert.equal(r.sha,HEAD);assert.equal(r.filesRead,2);assert.equal(x.api.calls.filter(x=>x.kind==='blob').length,2);assert.equal(r.requests,5);assert(!JSON.stringify(r).includes('PASSWORD'));});
test('reports do not contain file contents, token, or environment values',async()=>{const x=await setup({'.env.example':'PASSWORD=example_private_value','package.json':'{}'});await x.store.setToken('github_pat_this_is_just_a_test_123');await x.service.analyze(REF);const encoded=JSON.stringify(x.values.session['rr.reports']);assert(!encoded.includes('example_private_value'));assert(!encoded.includes('github_pat_'));assert(!encoded.includes('"files":'));assert(Object.values(x.values.session['rr.reports'])[0].report.env.some(x=>x.name==='PASSWORD'));});
test('token is only in protected session storage, preferences are local',async()=>{const x=await setup({});await x.store.setToken('test_token_with_20_characters');await x.store.language('ko');assert.equal(x.values.local['rr.settings'].language,'ko');assert(!JSON.stringify(x.values.local).includes('token'));assert(x.access.every(([,v])=>v==='TRUSTED_CONTEXTS'));});
test('warm report cache makes zero additional API requests',async()=>{const x=await setup({'package.json':'{}'});await x.service.analyze(REF);const n=x.api.calls.length;const r=await x.service.analyze(REF);assert(r.fromCache);assert.equal(x.api.calls.length,n);});
test('explicit refresh bypasses the report cache',async()=>{const x=await setup({'package.json':'{}'});await x.service.analyze(REF);const n=x.api.calls.length;await x.service.analyze(REF,'',true);assert.equal(x.api.calls.length,n*2);});
test('concurrent requests for the same scope share one scan',async()=>{const x=await setup({'package.json':'{}'});await Promise.all([x.service.analyze(REF),x.service.analyze(REF)]);assert.equal(x.api.calls.filter(x=>x.kind==='meta').length,1);});
test('setting a token clears old reports',async()=>{const x=await setup({'package.json':'{}'});await x.service.analyze(REF);await x.service.reset('test_token_with_20_characters');assert.deepEqual(x.values.session['rr.reports'],{});});
test('cache clear preserves the token but changes the session epoch',async()=>{const x=await setup({});await x.store.setToken('test_token_with_20_characters');const old=await x.store.auth();await x.service.reset();const next=await x.store.auth();assert.equal(old.token,next.token);assert.notEqual(old.epoch,next.epoch);});
test('expired cached results are not returned',async()=>{let now=1000;const x=store(()=>now);await x.store.ready;const epoch=(await x.store.auth()).epoch;await x.store.put('x',{x:1},epoch);now+=300001;assert.equal(await x.store.cached('x',epoch),null);});
test('session cache keeps at most eight reports',async()=>{const x=store();await x.store.ready;const epoch=(await x.store.auth()).epoch;for(let i=0;i<15;i++)await x.store.put(String(i),{i},epoch);assert.equal(Object.keys(x.values.session['rr.reports']).length,8);});
test('old-epoch report cannot be stored',async()=>{const x=store();await x.store.ready;const old=(await x.store.auth()).epoch;await x.store.setToken('test_token_with_20_characters');await assert.rejects(()=>x.store.put('x',{},old),e=>e.code==='AUTH_CHANGED');});
test('symlink setup files are never followed',async()=>{const x=await setup({},[{path:'package.json',type:'blob',mode:'120000',sha:'c'.repeat(40),size:10}]);const r=await x.service.analyze(REF);assert.equal(r.filesRead,0);assert(r.notices.some(x=>x.code==='nonRegular'));});
test('oversize file is skipped before a blob request',async()=>{const x=await setup({},[{path:'package.json',type:'blob',mode:'100644',sha:'c'.repeat(40),size:200000}]);const r=await x.service.analyze(REF);assert.equal(r.filesRead,0);assert(r.notices.some(x=>x.code==='oversize'));});
test('LFS pointer and binary data are not parsed',async()=>{const x=await setup({'package.json':'version https://git-lfs.github.com/spec/v1\noid sha256:x','README.md':'\u0000\u0001'});const r=await x.service.analyze(REF);assert.equal(r.filesRead,0);assert(r.notices.some(x=>x.code==='lfsPointer'));assert(r.notices.some(x=>x.code==='nonText'));});
test('empty repository produces a specific error',async()=>{const x=await setup({});const old=x.f.handler;x.f.handler=(kind,arg)=>kind==='head'?[]:old(kind,arg);await assert.rejects(()=>x.service.analyze(REF),e=>e.code==='EMPTY_REPO');});
test('nested directory is selected by tree SHA not guessed API paths',async()=>{const x=await setup({'package.json':'{}'},[{path:'apps',mode:'040000',type:'tree',sha:'c'.repeat(40)}]);const r=await x.service.analyze(REF,'apps');assert.equal(r.folder,'apps');assert(x.api.calls.some(x=>x.kind==='tree'&&x.arg==='c'.repeat(40)));assert(r.rows[0].evidence[0].url.includes(`/blob/${HEAD}/apps/package.json`));});
test('missing directory is not silently replaced with root',async()=>{const x=await setup({});await assert.rejects(()=>x.service.analyze(REF,'missing'),e=>e.code==='DIRECTORY_NOT_FOUND');});
test('truncated tree remains visibly partial',async()=>{const x=await setup({});const old=x.f.handler;x.f.handler=(kind,arg)=>kind==='tree'?{tree:[],truncated:true}:old(kind,arg);const r=await x.service.analyze(REF);assert(r.notices.some(x=>x.code==='partialTree'));});
test('blob request budget includes unsuccessful reads',async()=>{const files=Object.fromEntries(R.sourceNames.map(n=>[n,'test']));const x=await setup(files);const old=x.f.handler;x.f.handler=(kind,arg)=>kind==='blob'?{encoding:'none',content:'',size:1}:old(kind,arg);const r=await x.service.analyze(REF);assert.equal(x.api.calls.filter(x=>x.kind==='blob').length,14);assert(r.notices.some(x=>x.code==='fileLimit'));});
test('network errors abort instead of presenting a clean partial report',async()=>{const x=await setup({'package.json':'{}'});const old=x.api.get;x.api.get=async(...args)=>{if(args[1]==='blob')throw new R.Error('NETWORK');return old(...args);};await assert.rejects(()=>x.service.analyze(REF),e=>e.code==='NETWORK');assert(!Object.keys(x.values.session['rr.reports']||{}).length);});

test('total scan budget stops a prolonged sequence before another request',async()=>{const x=await setup({'package.json':'{}'});let time=0;x.service.now=()=>{time+=100000;return time;};await assert.rejects(()=>x.service.analyze(REF),e=>e.code==='TIMEOUT');assert.equal(x.api.calls.length,1);});
