import test from 'node:test';import assert from 'node:assert/strict';import {R,REF,store} from './helpers.mjs';
async function client(fetcher){const s=store();await s.store.ready;return {...s,api:new R.GitHub(s.store,fetcher),epoch:(await s.store.auth()).epoch};}
const response=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers});
test('native-style receiver stays bound to globalThis',async()=>{let called=0;const c=await client(function(url,init){assert.equal(this,globalThis);assert.equal(init.method,'GET');assert.equal(init.credentials,'omit');called++;return Promise.resolve(response({id:1}));});assert.deepEqual(await c.api.get(REF,'meta','',c.epoch),{id:1});assert.equal(called,1);});
test('diagnostics uses the same receiver-sensitive transport',async()=>{let calls=0;const c=await client(function(){assert.equal(this,globalThis);calls++;return Promise.resolve(response({resources:{}}));});const d=await c.api.diagnose();assert(d.anonymous.ok);assert.equal(d.authenticated,null);assert.equal(calls,1);});
test('token goes only into the API Authorization header',async()=>{const calls=[];const c=await client(async(url,init)=>{calls.push({url,init});return response({});});await c.store.setToken('github_pat_this_is_a_test_token_12345');await c.api.get(REF,'meta','',(await c.store.auth()).epoch);assert.equal(new URL(calls[0].url).origin,'https://api.github.com');assert.match(calls[0].init.headers.Authorization,/^Bearer /);assert.equal(calls[0].init.credentials,'omit');});
test('Illegal invocation is a programming error and is not retried',async()=>{let calls=0;const c=await client(()=>{calls++;throw new TypeError("Failed to execute 'fetch' on 'WorkerGlobalScope': Illegal invocation");});await assert.rejects(()=>c.api.get(REF,'meta','',c.epoch),e=>e.code==='CLIENT_ERROR');assert.equal(calls,1);});
test('network failures remain distinct from JSON failures',async()=>{const c=await client(()=>Promise.reject(new TypeError('Failed to fetch')));await assert.rejects(()=>c.api.get(REF,'meta','',c.epoch),e=>e.code==='NETWORK');});
test('a successful non-JSON body is BAD_RESPONSE not NETWORK',async()=>{const c=await client(()=>Promise.resolve(new Response('oops',{status:200})));await assert.rejects(()=>c.api.get(REF,'meta','',c.epoch),e=>e.code==='BAD_RESPONSE');});
for(const [status,code]of [[401,'TOKEN_REJECTED'],[403,'FORBIDDEN'],[404,'NOT_FOUND'],[409,'EMPTY_REPO'],[500,'GITHUB_UNAVAILABLE'],[422,'API_ERROR']])test(`HTTP ${status} maps to ${code}`,async()=>{const c=await client(()=>Promise.resolve(response({message:'error'},status)));await assert.rejects(()=>c.api.get(REF,'meta','',c.epoch),e=>e.code===code&&e.status===status);});
test('rate limit is distinguished from ordinary 403',async()=>{const c=await client(()=>Promise.resolve(response({message:'API rate limit'},403,{'x-ratelimit-remaining':'0','x-ratelimit-reset':String(Math.floor(Date.now()/1000)+100)})));await assert.rejects(()=>c.api.get(REF,'meta','',c.epoch),e=>e.code==='RATE_LIMIT'&&e.retryAt>Date.now());});
test('active cooldown prevents another core request',async()=>{let n=0;const c=await client(()=>{n++;return Promise.resolve(response({}));});await c.store.setRate({retryAt:Date.now()+10000},c.epoch);await assert.rejects(()=>c.api.get(REF,'meta','',c.epoch),e=>e.code==='RATE_LIMIT');assert.equal(n,0);});
test('oversized response is rejected',async()=>{const c=await client(()=>Promise.resolve(new Response('{}',{headers:{'content-length':'3000000'}})));await assert.rejects(()=>c.api.get(REF,'meta','',c.epoch),e=>e.code==='TOO_LARGE');});
test('untrusted final response origin is rejected',async()=>{const c=await client(()=>{const r=response({});Object.defineProperty(r,'url',{value:'https://evil.example/x'});return Promise.resolve(r);});await assert.rejects(()=>c.api.get(REF,'meta','',c.epoch),e=>e.code==='UNSAFE_REDIRECT');});
test('credentials changed in-flight invalidate the response',async()=>{let release,started;const ready=new Promise(r=>started=r);const c=await client(()=>{started();return new Promise(r=>release=r);});const result=c.api.get(REF,'meta','',c.epoch);await ready;await c.store.setToken('test_token_with_at_least_20_chars');release(response({}));await assert.rejects(()=>result,e=>e.code==='AUTH_CHANGED');});
test('endpoint builder cannot target another origin or arbitrary API path',async()=>{const c=await client(()=>Promise.resolve(response({})));assert.throws(()=>c.api.endpoint(REF,'https://evil.example'));assert.throws(()=>c.api.endpoint(REF,'blob','../foo'));});
test('branch slashes are query-encoded, not injected as URL paths',async()=>{const c=await client(()=>Promise.resolve(response({})));const u=new URL(c.api.endpoint(REF,'head','feature/a&x=1'));assert.equal(u.searchParams.get('sha'),'feature/a&x=1');assert.equal(u.searchParams.get('x'),null);});
