(() => {
  'use strict';
  const R = globalThis.RepoRun;
  R.strings = {
    en: {
      tagline:'Know the setup before you clone.',launcherNote: 'Requirements before cloning', button:'Run setup',open:'Inspect run requirements',close:'Close',settings:'Settings',language:'Switch language',
      intro:'Read the declared setup, not a guessed installation guide.',scope:'Directory on default branch',root:'Repository root',analyze:'Inspect',refresh:'Refresh',loading:'Reading setup files…',loadingNote:'Resolving a fixed commit and reading a small set of configuration files. Nothing is executed.',
      overview:'Overview',commands:'Commands',evidence:'Evidence',declared:'Declared',inferred:'Inferred',unknown:'Not established',statusLegend:'Declared = found in a file. Inferred = a clue, not a requirement. Not established = insufficient evidence.',
      project:'Project type',runtime:'Runtime declarations',manager:'Package manager',build:'Build script',workspace:'Workspace',platform:'OS / CPU declarations',framework:'Declared tools',extension:'Browser extension',deploymentFiles:'Configuration files',staticDeploy:'Static hosting compatibility',
      packageNotGuarantee:'A package manifest is present. This is not proof the project builds or starts.',htmlNotGuarantee:'An index.html file exists. Referenced assets, APIs and file:// compatibility are not tested.',unsupported:'No supported package manifest or HTML entry was established in this directory. Inspect a subdirectory or the README.',
      versionsNotResolved:'These declarations are shown separately. Version ranges are not resolved or checked for compatibility.',versionNotInstalled:'A repository declaration, not a check of software installed on your computer.',managerDeclaration:'The project declares this manager. Its installation and version were not verified.',lockHint:'Inferred from lockfile names only; lockfile contents are not read.',
      buildNotExecuted:'Only a declared build script is reported. No install, build or runtime test is performed.',workspaceNotExpanded:'Workspace declarations are shown, not expanded. Inspect an individual directory explicitly.',noDeviceCheck:'No hardware or operating-system check is performed.',frameworkNotDeploy:'A dependency declaration does not establish deployment mode or a required external service.',extensionNotWeb:'This manifest describes a browser extension, not a standalone website.',configNotExecuted:'Presence only. Executable configuration files are not evaluated.',staticNotGuaranteed:'RepoRun does not certify GitHub Pages or other static hosting compatibility.',
      environment:'Environment variable names',envNote:'Names from example/template files only. Values are discarded; presence does not prove a variable is required.',noEnv:'No variable names were extracted from the supported example files in this scope.',containers:'Container clues',noServices:'No supported container declaration was extracted. This does not prove external services are unnecessary.',image:'Docker FROM',compose:'Compose file',dockerNotRequired:'Base-image declaration only; a Dockerfile does not prove Docker is required for all usage.',composeNotParsed:'File present. Services, interpolation, profiles and overrides are not resolved.',
      scriptNote:'Literal scripts from package.json, not verified launch instructions. A package manager may supply PATH entries and run pre/post hooks. Copying does not execute anything.',noCommands:'No readable package.json scripts were found in this directory.',copy:'Copy script text',copied:'Copied',copyFailed:'Clipboard unavailable. Select and copy the visible text.',copyBlocked:'Copy disabled: content was redacted, truncated or contains control/multiline text.',hook:'Install / lifecycle hook',
      readme:'README command examples',readmeNote:'A small sample of shell-like fenced lines from this directory’s README. Context and multi-line sequences may be incomplete. Open the source before use.',noReadme:'No matching shell command examples were extracted.',
      filesTitle:'Files examined',presence:'Presence only',read:'Read',skipped:'Skipped',error:'Read failed',file:'File',treatment:'Treatment',source:'Source',openSource:'Open source',scopeNote:'Only the selected directory is inspected. Parent configuration, nested packages, CI workflows and runtime behavior are not resolved.',
      notices:'Review notes',invalidJson:'A JSON file could not be parsed.',mixedManagers:'Multiple package managers are indicated. Review declarations and lockfiles before choosing one.',installHooks:'Installation/lifecycle scripts are present. Review these before running a package manager.',scriptLimit:'Only the first 40 scripts are shown.',envLimit:'Variable names are capped at 100.',runtimeFileLimit:'Only the first 30 Node declarations in .tool-versions are shown.',dockerImageLimit:'Only the first 20 Docker base-image declarations are shown.',folderScope:'Parent-level runtime settings and workspace configuration are not inherited in this directory report.',partialTree:'The file listing is incomplete. Missing files cannot be treated as absent.',nonRegular:'A symlink, submodule or non-regular entry was not followed.',oversize:'A file exceeded the 128 KiB inspection limit.',fileLimit:'A file was left unread because the 14-file request budget was reached.',invalidBlob:'A file did not have a usable Git blob identifier.',lfsPointer:'A Git LFS pointer was not followed.',nonText:'A binary or non-text file was not parsed.',fileReadFailed:'A selected file could not be read as UTF-8 text.',skippedFile:'A file was skipped.',
      cached:'Session cache',fresh:'New inspection',pinned:'Pinned commit',inspected:'Inspected',filesRead:'files read',apiRequests:'API requests',defaultOnly:'Default branch only, even when another branch is open.',export:'Export report',exportConfirm:'The report may contain private repository paths and literal commands. Inspect it before sharing. Download a Markdown copy?',nothingRun:'READ-ONLY · NO COMMANDS EXECUTED',retry:'Try again',empty:'Nothing to inspect yet.',stateChanged:'Session credentials or cache changed. Inspect again to get a fresh report.',
      optionsTitle:'RepoRun settings',optionsIntro:'GitHub access is optional for public repositories. Nothing is sent to a RepoRun server.',interface:'Interface language',tokenTitle:'Optional GitHub token',tokenNote:'Use a fine-grained personal access token scoped to the repositories you need, with Contents: read-only. Browser GitHub login is not API authentication.',tokenPlaceholder:'Paste a GitHub personal access token',saveToken:'Save for this session',removeToken:'Remove token',hasToken:'A session token is stored.',noToken:'No session token is stored.',saved:'Session token saved. Cached reports were cleared. Connection has not yet been verified.',removed:'Session token removed. Cached reports were cleared.',sessionNote:'Tokens are not saved to disk by this extension. Chrome clears session storage on restart, reload, disable or update. Session storage is not an encrypted vault.',
      diagnosticTitle:'GitHub API diagnostics',diagnosticNote:'Checks the fixed /rate_limit endpoint. A successful response is not proof of access to a particular private repository.',diagnose:'Check API connection',diagnosing:'Checking…',anonymous:'Without token',authenticated:'With saved token',notRun:'Not run',permission:'API host permission',granted:'Granted',withheld:'Missing or withheld',restore:'Request API access',restored:'API host access granted.',denied:'API host access was not granted.',cacheTitle:'Temporary reports',cacheNote:'Normalized reports are cached for five minutes in session storage (up to eight reports). Raw configuration files and .env example values are not persisted. Clearing affects open reports in GitHub tabs.',clearCache:'Clear report cache',cleared:'Cached reports were cleared.',privacy:'Privacy policy',help:'User guide',independent:'Independent extension. Not affiliated with GitHub or Google.',onGithub:'Open a GitHub repository, then select Run setup.',openSettings:'Open settings',
      errors:{INVALID_INPUT:'This repository or directory input is not supported.',INVALID_TOKEN:'The token format is invalid. Paste only the token value.',TOKEN_REJECTED:'GitHub rejected the token (401). Check its value and expiration.',FORBIDDEN:'Access was denied. Check repository selection, Contents read permission, and organization approval.',NOT_FOUND:'GitHub could not find or disclose the repository. A private repository may require an authorized token.',EMPTY_REPO:'This repository has no readable default-branch commit yet.',DIRECTORY_NOT_FOUND:'The requested directory was not found in the returned tree. Use a directory on the default branch.',RATE_LIMIT:'GitHub’s API limit was reached. Wait until the retry time or use an authorized token.',NETWORK:'The browser could not complete the GitHub API request. Check host access and the connection diagnostics.',CLIENT_ERROR:'A native API invocation failed inside the extension. This is not a token permission error.',TIMEOUT:'The GitHub request timed out. Retry later.',BAD_RESPONSE:'GitHub returned data that RepoRun could not safely interpret.',TOO_LARGE:'The API response exceeded the inspection size limit.',GITHUB_UNAVAILABLE:'GitHub is temporarily unavailable.',API_ERROR:'GitHub returned an unexpected HTTP status.',UNSAFE_REDIRECT:'A response redirected outside the permitted GitHub API scope.',AUTH_CHANGED:'Credentials or session state changed while inspecting. Inspect again.',BUSY:'Three inspections are already running. Wait for one to finish.',INTERNAL:'An internal extension error occurred.',EXTENSION_RELOADED:'The extension was reloaded. Refresh this GitHub page.'}
    },
    ko: {
      runtimeFileLimit:'.tool-versions의 Node 선언은 처음 30개만 표시합니다.',dockerImageLimit:'Docker 기본 이미지 선언은 처음 20개만 표시합니다.',
      tagline:'클론 전에 실행 조건부터.',launcherNote: '클론 전 요구사항 확인', button:'실행 조건',open:'실행 조건 확인',close:'닫기',settings:'설정',language:'언어 전환',intro:'추측한 설치법이 아니라, 파일에 명시된 조건을 확인합니다.',scope:'기본 브랜치의 디렉터리',root:'저장소 루트',analyze:'분석',refresh:'새로 확인',loading:'실행 조건을 읽고 있습니다…',loadingNote:'커밋을 고정한 뒤 일부 설정 파일만 읽습니다. 명령을 실행하지 않습니다.',
      overview:'개요',commands:'명령',evidence:'근거 파일',declared:'명시됨',inferred:'추정됨',unknown:'확인되지 않음',statusLegend:'명시됨: 파일에서 확인한 선언. 추정됨: 단서일 뿐 필수 조건은 아님. 확인되지 않음: 근거 부족.',
      project:'프로젝트 유형',runtime:'런타임 선언',manager:'패키지 관리자',build:'빌드 스크립트',workspace:'워크스페이스',platform:'운영체제 / CPU 선언',framework:'선언된 도구',extension:'브라우저 확장',deploymentFiles:'설정 파일',staticDeploy:'정적 호스팅 호환성',
      packageNotGuarantee:'패키지 매니페스트가 있습니다. 빌드나 실행 성공을 확인한 것은 아닙니다.',htmlNotGuarantee:'index.html이 있습니다. 연결된 파일·API 및 file:// 호환성은 검증하지 않습니다.',unsupported:'이 디렉터리에서 지원하는 패키지 매니페스트나 HTML 진입점을 확인하지 못했습니다. 하위 디렉터리 또는 README를 확인하세요.',
      versionsNotResolved:'각 선언을 별도로 표시합니다. 버전 범위를 계산하거나 상호 호환성을 판정하지 않습니다.',versionNotInstalled:'저장소의 선언이며, 사용자 PC에 설치된 소프트웨어를 확인한 결과가 아닙니다.',managerDeclaration:'프로젝트가 명시한 관리자입니다. 설치 여부나 버전은 검증하지 않습니다.',lockHint:'잠금 파일 이름에서 추정한 결과입니다. 잠금 파일 본문은 읽지 않습니다.',buildNotExecuted:'선언된 빌드 스크립트만 표시합니다. 설치·빌드·실행 테스트를 수행하지 않습니다.',workspaceNotExpanded:'선언만 표시하며 워크스페이스를 일괄 탐색하지 않습니다. 개별 디렉터리를 직접 지정하세요.',noDeviceCheck:'사용자 기기의 하드웨어나 운영체제를 검사하지 않습니다.',frameworkNotDeploy:'의존성 선언만으로 배포 방식이나 외부 서비스의 필요성을 확정하지 않습니다.',extensionNotWeb:'브라우저 확장 매니페스트이며 독립 웹사이트를 의미하지 않습니다.',configNotExecuted:'파일 존재만 확인합니다. 실행형 설정 파일을 평가하지 않습니다.',staticNotGuaranteed:'GitHub Pages 등 정적 호스팅과의 호환성을 보증하지 않습니다.',
      environment:'환경변수 이름',envNote:'예제·템플릿 파일의 변수명만 추출합니다. 값은 보관하지 않으며, 변수 존재가 필수 사용을 뜻하지는 않습니다.',noEnv:'이 범위의 지원하는 예제 파일에서 변수명을 추출하지 못했습니다.',containers:'컨테이너 관련 단서',noServices:'지원하는 컨테이너 선언을 추출하지 못했습니다. 외부 서비스가 불필요하다는 의미는 아닙니다.',image:'Docker FROM',compose:'Compose 파일',dockerNotRequired:'기반 이미지 선언입니다. Dockerfile이 있다고 모든 실행에 Docker가 필수인 것은 아닙니다.',composeNotParsed:'파일 존재만 확인합니다. 서비스·변수 치환·프로필·덮어쓰기는 해석하지 않습니다.',
      scriptNote:'package.json에 적힌 스크립트 원문입니다. 검증된 실행 안내가 아닙니다. 패키지 관리자가 PATH와 사전·사후 훅을 적용할 수 있습니다. 복사만으로 실행되지는 않습니다.',noCommands:'이 디렉터리에서 읽을 수 있는 package.json 스크립트를 찾지 못했습니다.',copy:'스크립트 복사',copied:'복사됨',copyFailed:'클립보드에 접근할 수 없습니다. 화면의 텍스트를 선택해 복사하세요.',copyBlocked:'민감정보 가림·길이 제한·제어문자 또는 여러 줄 때문에 복사를 제한했습니다.',hook:'설치 / 생명주기 훅',readme:'README 명령 예시',readmeNote:'현재 디렉터리 README의 셸 코드 블록 일부입니다. 문맥이나 여러 줄 명령이 누락될 수 있으니 실행 전에 원문을 확인하세요.',noReadme:'조건에 맞는 셸 명령 예시를 추출하지 못했습니다.',
      filesTitle:'확인한 파일',presence:'존재만 확인',read:'읽음',skipped:'건너뜀',error:'읽기 실패',file:'파일',treatment:'처리 상태',source:'근거',openSource:'원문 열기',scopeNote:'지정한 디렉터리만 분석합니다. 상위 설정·중첩 패키지·CI 워크플로·실제 실행 동작은 해석하지 않습니다.',notices:'검토 사항',invalidJson:'JSON 파일을 해석하지 못했습니다.',mixedManagers:'서로 다른 패키지 관리자의 단서가 있습니다. 선언과 잠금 파일을 확인하세요.',installHooks:'설치 또는 생명주기 스크립트가 있습니다. 패키지 관리자 실행 전에 검토하세요.',scriptLimit:'스크립트는 처음 40개까지만 표시합니다.',envLimit:'환경변수는 최대 100개까지만 표시합니다.',folderScope:'현재 디렉터리 결과에는 상위 런타임·워크스페이스 설정을 상속하지 않습니다.',partialTree:'파일 목록이 일부만 반환됐습니다. 표시되지 않는 파일을 없는 것으로 판단하면 안 됩니다.',nonRegular:'심볼릭 링크·서브모듈·일반 파일이 아닌 항목은 따라가지 않았습니다.',oversize:'파일이 128 KiB 분석 제한을 넘었습니다.',fileLimit:'본문 요청 예산 14개를 초과해 읽지 않았습니다.',invalidBlob:'유효한 Git 블롭 식별자를 확인하지 못했습니다.',lfsPointer:'Git LFS 포인터의 실제 파일을 가져오지 않았습니다.',nonText:'바이너리 또는 텍스트가 아닌 파일은 분석하지 않았습니다.',fileReadFailed:'선택한 파일을 UTF-8 텍스트로 읽지 못했습니다.',skippedFile:'파일을 건너뛰었습니다.',
      cached:'세션 캐시',fresh:'새 분석',pinned:'고정 커밋',inspected:'확인 시각',filesRead:'개 파일 읽음',apiRequests:'회 API 요청',defaultOnly:'다른 브랜치를 보고 있어도 기본 브랜치만 분석합니다.',export:'보고서 내보내기',exportConfirm:'보고서에 비공개 저장소 경로와 명령 원문이 포함될 수 있습니다. 공유 전 내용을 확인하세요. Markdown 파일로 내려받겠습니까?',nothingRun:'읽기 전용 · 명령 실행 없음',retry:'다시 시도',empty:'아직 분석 결과가 없습니다.',stateChanged:'인증 또는 세션 캐시가 변경됐습니다. 다시 분석하세요.',
      optionsTitle:'RepoRun 설정',optionsIntro:'공개 저장소에서는 인증이 선택 사항입니다. RepoRun 서버로 전송하지 않습니다.',interface:'화면 언어',tokenTitle:'GitHub 토큰 (선택)',tokenNote:'필요한 저장소만 선택하고 Contents 읽기 권한을 부여한 fine-grained PAT를 사용하세요. GitHub 웹 로그인과 API 인증은 별개입니다.',tokenPlaceholder:'GitHub 개인 액세스 토큰 붙여넣기',saveToken:'현재 세션에 저장',removeToken:'토큰 삭제',hasToken:'세션 토큰이 저장되어 있습니다.',noToken:'저장된 세션 토큰이 없습니다.',saved:'세션 토큰을 저장하고 캐시를 비웠습니다. 연결 성공을 검증한 것은 아닙니다.',removed:'세션 토큰과 캐시를 삭제했습니다.',sessionNote:'확장 자체는 토큰을 디스크에 저장하지 않습니다. Chrome 재시작·재로드·비활성화·업데이트 시 세션 정보가 삭제됩니다. 세션 저장소는 암호화 금고가 아닙니다.',
      diagnosticTitle:'GitHub API 연결 진단',diagnosticNote:'고정된 /rate_limit 엔드포인트를 확인합니다. 응답 성공이 특정 비공개 저장소의 접근 권한을 보증하지는 않습니다.',diagnose:'API 연결 확인',diagnosing:'진단 중…',anonymous:'토큰 없이',authenticated:'저장한 토큰으로',notRun:'실행하지 않음',permission:'API 호스트 권한',granted:'허용됨',withheld:'없거나 보류됨',restore:'API 접근 권한 요청',restored:'API 호스트 접근이 허용됐습니다.',denied:'API 호스트 접근이 허용되지 않았습니다.',cacheTitle:'임시 보고서',cacheNote:'정규화한 보고서는 세션에 5분간 캐시합니다(최대 8개). 설정 원문과 환경변수 예제 값은 영구 저장하지 않습니다. 캐시 삭제 시 열려 있는 패널도 무효화됩니다.',clearCache:'보고서 캐시 비우기',cleared:'보고서 캐시를 비웠습니다.',privacy:'개인정보 처리방침',help:'사용 안내',independent:'GitHub·Google과 무관한 독립 확장프로그램입니다.',onGithub:'GitHub 저장소를 열고 실행 조건 버튼을 선택하세요.',openSettings:'설정 열기',
      errors:{INVALID_INPUT:'지원하지 않는 저장소 또는 디렉터리 입력입니다.',INVALID_TOKEN:'토큰 형식이 잘못됐습니다. 토큰 값만 붙여넣으세요.',TOKEN_REJECTED:'GitHub가 토큰을 거부했습니다(401). 값과 유효기간을 확인하세요.',FORBIDDEN:'접근이 거부됐습니다. 저장소 선택·Contents 읽기 권한·조직 승인을 확인하세요.',NOT_FOUND:'GitHub가 저장소를 찾거나 공개할 수 없습니다. 비공개 저장소에는 적절한 토큰이 필요할 수 있습니다.',EMPTY_REPO:'읽을 수 있는 기본 브랜치 커밋이 아직 없습니다.',DIRECTORY_NOT_FOUND:'반환된 트리에서 디렉터리를 찾지 못했습니다. 기본 브랜치의 경로를 지정하세요.',RATE_LIMIT:'GitHub API 한도에 도달했습니다. 재시도 시각까지 기다리거나 인증 토큰을 사용하세요.',NETWORK:'GitHub API 요청을 완료하지 못했습니다. 호스트 권한과 연결 진단을 확인하세요.',CLIENT_ERROR:'확장 내부의 네이티브 API 호출 오류입니다. 토큰 권한 문제는 아닙니다.',TIMEOUT:'GitHub 요청 시간이 초과됐습니다. 잠시 후 다시 시도하세요.',BAD_RESPONSE:'GitHub 응답을 안전하게 해석하지 못했습니다.',TOO_LARGE:'API 응답이 크기 제한을 초과했습니다.',GITHUB_UNAVAILABLE:'GitHub가 일시적으로 응답하지 않습니다.',API_ERROR:'예상하지 못한 HTTP 상태를 받았습니다.',UNSAFE_REDIRECT:'허용한 GitHub API 범위 밖으로 이동한 응답을 차단했습니다.',AUTH_CHANGED:'분석 도중 인증 또는 세션 상태가 변경됐습니다. 다시 분석하세요.',BUSY:'이미 분석 3개가 진행 중입니다. 완료 후 다시 시도하세요.',INTERNAL:'확장 내부 오류가 발생했습니다.',EXTENSION_RELOADED:'확장이 다시 로드됐습니다. GitHub 페이지를 새로고침하세요.'}
    }
  };
  R.t = (lang,key) => R.strings[lang]?.[key] ?? R.strings.en[key] ?? key;
  R.errorText = (error,lang) => `${R.strings[lang]?.errors?.[error?.code] || R.strings.en.errors[error?.code] || R.strings.en.errors.INTERNAL}${error?.status ? ` (HTTP ${error.status})` : ''}${error?.detail ? ` [${R.clean(error.detail,180)}]` : ''}${error?.retryAt ? ` ${new Date(error.retryAt).toLocaleString(lang === 'ko' ? 'ko-KR' : 'en-US')}` : ''}`;
})();
